
[package]
name = "snake"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]

[dependencies]
#amethyst = { git = "https://github.com/amethyst/amethyst", commit = "4e3d39704e7dfb11154e3bde5d32dad650f5e7a3", branch = "develop" }
amethyst = { path = "../amethyst" }
specs = "0.9.2"
